services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/datalog:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    # depends_on:
    #   - zookeeper
    ports:
      - 9096:9096
      - 19096:19096
    environment:
      KAFKA_BROKER_ID: 2
      # producer ต้องเอาเป็น zookeeper
      # consumer ต้งเอาเป็น ip ของ producer
      KAFKA_ZOOKEEPER_CONNECT: 192.168.43.113:2181 
      KAFKA_LISTENERS: INTERNAL://:19096,EXTERNAL://:9096
      # producer เอาเป็น ip kafka
      # consumer เอาเป็น ip ตัวเอง
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://192.168.43.113:19096,EXTERNAL://192.168.43.113:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 3
      # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper
  
  # kafka_2:
  #   image: confluentinc/cp-kafka:latest
  #   volumes:
  #     - ./kafka/kafka2/data:/var/lib/kafka/data
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9093:9093
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: INTERNAL://:19093,EXTERNAL://:9093
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_2:19093,EXTERNAL://localhost:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  
  # kafka_3:
  #   image: confluentinc/cp-kafka:latest
  #   volumes:
  #     - ./kafka/kafka_3/data:/var/lib/kafka/data
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9094:9094
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: INTERNAL://:19094,EXTERNAL://:9094
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_3:19094,EXTERNAL://localhost:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9096 , 192.168.43.11:9096, 192.168.43.194:9096, 192.168.43.147:9096"
    depends_on:
      - kafka